# Generated by Django 4.2.1 on 2023-06-01 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='track',
            name='playlist',
        ),
        migrations.AddField(
            model_name='artist',
            name='informations',
            field=models.CharField(default='info', max_length=200),
        ),
        migrations.AddField(
            model_name='artist',
            name='tracks',
            field=models.CharField(default='music', max_length=50),
        ),
        migrations.AddField(
            model_name='playlist',
            name='total_tracks',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='lyrics',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='playlists',
            field=models.ManyToManyField(to='MyApp.playlist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='PodCasts',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.creator')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tracks', models.CharField(max_length=255)),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_year', models.CharField(default='Valor padrão', max_length=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.artist')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.album'),
        ),
    ]
